const KEY='siperpus_sd_v1';
const seed={users:[{username:'admin',password:'admin123',name:'Administrator',role:'admin'}],books:[],members:[],transactions:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const dateNow=()=>new Date().toISOString().slice(0,10);
function showPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('#page-'+p).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#pageTitle').textContent={dashboard:'Dashboard',books:'Data Buku',members:'Data Anggota',transactions:'Transaksi'}[p]; if(p==='dashboard')renderDashboard();if(p==='books')renderBooks();if(p==='members')renderMembers();if(p==='transactions')renderTransactions()}
function renderDashboard(){let borrowed=db.transactions.filter(t=>t.status==='borrowed');let late=borrowed.filter(t=>t.due_date<dateNow());$('#statBooks').textContent=db.books.reduce((a,b)=>a+Number(b.stock||0),0);$('#statMembers').textContent=db.members.length;$('#statBorrowed').textContent=borrowed.length;$('#statLate').textContent=late.length;$('#recentTransactions').innerHTML=db.transactions.slice(-5).reverse().map(t=>`<p><b>${esc(t.code)}</b> — ${esc(t.member_name)} meminjam ${esc(t.book_title)}</p>`).join('')||'<div class="empty">Belum ada transaksi.</div>'}
function renderBooks(){let q=($('#bookSearch').value||'').toLowerCase();$('#booksTable').innerHTML=db.books.filter(b=>[b.code,b.title,b.author,b.category,b.class_level].join(' ').toLowerCase().includes(q)).map(b=>`<tr><td>${esc(b.code)}</td><td>${esc(b.title)}</td><td>${esc(b.author)}</td><td>${esc(b.category)}</td><td>${esc(b.class_level)}</td><td>${b.available??b.stock}/${b.stock}</td><td><button onclick="editBook('${b.id}')">Edit</button></td></tr>`).join('')||'<tr><td colspan="7">Belum ada buku.</td></tr>'}
function renderMembers(){let q=($('#memberSearch').value||'').toLowerCase();$('#membersTable').innerHTML=db.members.filter(m=>[m.member_code,m.name,m.nis,m.class_name].join(' ').toLowerCase().includes(q)).map(m=>`<tr><td>${esc(m.member_code)}</td><td>${esc(m.name)}</td><td>${esc(m.type)}</td><td>${esc(m.class_name)}</td><td>${esc(m.nis)}</td><td><span class="badge available">Aktif</span></td><td><button onclick="editMember('${m.id}')">Edit</button></td></tr>`).join('')||'<tr><td colspan="7">Belum ada anggota.</td></tr>'}
function renderTransactions(){ $('#transactionsTable').innerHTML=db.transactions.slice().reverse().map(t=>{let late=t.status==='borrowed'&&t.due_date<dateNow();return `<tr><td>${esc(t.code)}</td><td>${esc(t.member_name)}</td><td>${esc(t.book_title)}</td><td>${t.borrow_date}</td><td>${t.due_date}</td><td>${t.return_date||'-'}</td><td><span class="badge ${late?'late':t.status==='returned'?'available':'borrowed'}">${late?'Terlambat':t.status==='returned'?'Dikembalikan':'Dipinjam'}</span></td></tr>`}).join('')||'<tr><td colspan="7">Belum ada transaksi.</td></tr>'}
function modal(title,html,handler){$('#modalTitle').textContent=title;$('#modalForm').innerHTML=html;$('#modalForm').onsubmit=e=>{e.preventDefault();handler(new FormData(e.target));$('#modal').classList.add('hidden')};$('#modal').classList.remove('hidden')}
function addBook(existing){modal(existing?'Edit Buku':'Tambah Buku',`<label>Kode Buku</label><input name="code" required value="${esc(existing?.code)}"><label>ISBN</label><input name="isbn" value="${esc(existing?.isbn)}"><label>Judul</label><input name="title" required value="${esc(existing?.title)}"><label>Pengarang</label><input name="author" value="${esc(existing?.author)}"><label>Penerbit</label><input name="publisher" value="${esc(existing?.publisher)}"><label>Tahun</label><input name="year" type="number" value="${esc(existing?.year)}"><label>Kategori</label><input name="category" value="${esc(existing?.category)}"><label>Kelas</label><input name="class_level" value="${esc(existing?.class_level)}"><label>Rak</label><input name="rack" value="${esc(existing?.rack)}"><label>Jumlah Stok</label><input name="stock" type="number" min="1" required value="${existing?.stock||1}"><button>Simpan</button>`,f=>{let x=Object.fromEntries(f);x.id=existing?.id||id();x.stock=Number(x.stock);if(existing){let old=existing.stock,delta=x.stock-old;x.available=Math.max(0,(existing.available??old)+delta);Object.assign(existing,x)}else{x.available=x.stock;db.books.push(x)}save();renderBooks();renderDashboard()})}
window.editBook=x=>addBook(db.books.find(b=>b.id===x));
function addMember(existing){modal(existing?'Edit Anggota':'Tambah Anggota',`<label>No. Anggota</label><input name="member_code" required value="${esc(existing?.member_code)}"><label>Nama</label><input name="name" required value="${esc(existing?.name)}"><label>Tipe</label><select name="type"><option ${existing?.type==='siswa'?'selected':''}>siswa</option><option ${existing?.type==='guru'?'selected':''}>guru</option></select><label>Kelas</label><input name="class_name" value="${esc(existing?.class_name)}"><label>NIS</label><input name="nis" value="${esc(existing?.nis)}"><button>Simpan</button>`,f=>{let x=Object.fromEntries(f);x.id=existing?.id||id();if(existing)Object.assign(existing,x);else db.members.push(x);save();renderMembers();renderDashboard()})}
window.editMember=x=>addMember(db.members.find(m=>m.id===x));
function borrow(){if(!db.members.length||!db.books.length)return alert('Tambahkan anggota dan buku terlebih dahulu.');modal('Peminjaman',`<label>Anggota</label><select name="member_id" required>${db.members.map(m=>`<option value="${m.id}">${esc(m.member_code)} — ${esc(m.name)}</option>`).join('')}</select><label>Buku</label><select name="book_id" required>${db.books.filter(b=>(b.available??0)>0).map(b=>`<option value="${b.id}">${esc(b.code)} — ${esc(b.title)} (tersedia ${b.available})</option>`).join('')}</select><label>Jatuh Tempo</label><input name="due_date" type="date" required value="${new Date(Date.now()+7*864e5).toISOString().slice(0,10)}"><button>Proses Peminjaman</button>`,f=>{let x=Object.fromEntries(f),m=db.members.find(a=>a.id===x.member_id),b=db.books.find(a=>a.id===x.book_id);if(!b||b.available<1)return alert('Stok tidak tersedia.');db.transactions.push({id:id(),code:'TRX-'+Date.now(),member_id:m.id,member_name:m.name,book_id:b.id,book_title:b.title,borrow_date:dateNow(),due_date:x.due_date,return_date:null,status:'borrowed',fine:0});b.available--;save();renderTransactions();renderDashboard()})}
function ret(){let active=db.transactions.filter(t=>t.status==='borrowed');if(!active.length)return alert('Tidak ada buku yang sedang dipinjam.');modal('Pengembalian',`<label>Transaksi</label><select name="trx_id">${active.map(t=>`<option value="${t.id}">${esc(t.code)} — ${esc(t.member_name)} — ${esc(t.book_title)}</option>`).join('')}</select><button>Proses Pengembalian</button>`,f=>{let t=db.transactions.find(x=>x.id===Object.fromEntries(f).trx_id);t.status='returned';t.return_date=dateNow();let b=db.books.find(x=>x.id===t.book_id);if(b)b.available++;save();renderTransactions();renderDashboard()})}
$('#loginForm').onsubmit=e=>{e.preventDefault();let u=db.users.find(x=>x.username===$('#username').value&&x.password===$('#password').value);if(!u)return $('#loginError').textContent='Username atau password salah.';sessionStorage.setItem('siperpus_user',u.name);$('#loginPage').classList.add('hidden');$('#app').classList.remove('hidden');$('#userName').textContent=u.name;showPage('dashboard')};
$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('siperpus_user');location.reload()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$('#addBookBtn').onclick=()=>addBook();$('#addMemberBtn').onclick=()=>addMember();$('#borrowBtn').onclick=borrow;$('#returnBtn').onclick=ret;$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#bookSearch').oninput=renderBooks;$('#memberSearch').oninput=renderMembers;$('#today').textContent=new Date().toLocaleDateString('id-ID',{dateStyle:'full'});
if(sessionStorage.getItem('siperpus_user')){$('#loginPage').classList.add('hidden');$('#app').classList.remove('hidden');$('#userName').textContent=sessionStorage.getItem('siperpus_user');showPage('dashboard')}
